// <auto-generated />
using System;
using GestorTareasIntegrador.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorTareasIntegrador.Migrations
{
    [DbContext(typeof(TareasDbContext))]
    [Migration("20260702051209_InicialConSeed")]
    partial class InicialConSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("GestorTareasIntegrador.Models.CategoriaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Estudio"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Trabajo"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Personal"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Hogar"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Proyectos"
                        });
                });

            modelBuilder.Entity("GestorTareasIntegrador.Models.TareaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Prioridad");

                    b.HasIndex("Titulo");

                    b.ToTable("Tareas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Completada = true,
                            CreadaEn = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Verificar con dotnet --version",
                            FechaVencimiento = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Prioridad = "Alta",
                            Titulo = "Instalar .NET 10 SDK"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Completada = false,
                            CreadaEn = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Clase 3 - binding bidireccional",
                            FechaVencimiento = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Prioridad = "Media",
                            Titulo = "Repasar Data Binding"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 5,
                            Completada = false,
                            CreadaEn = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Con DataAnnotationsValidator",
                            FechaVencimiento = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Prioridad = "Alta",
                            Titulo = "Armar EditForm de alta"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 5,
                            Completada = false,
                            CreadaEn = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Archivos .razor.css",
                            FechaVencimiento = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Prioridad = "Baja",
                            Titulo = "Configurar CSS Isolation"
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 5,
                            Completada = false,
                            CreadaEn = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Cards responsive",
                            FechaVencimiento = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Prioridad = "Media",
                            Titulo = "Aplicar grilla Bootstrap"
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 5,
                            Completada = false,
                            CreadaEn = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "JS Interop + localStorage",
                            FechaVencimiento = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Prioridad = "Media",
                            Titulo = "Implementar modo oscuro"
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 2,
                            Completada = true,
                            CreadaEn = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "EF Core + SQLite",
                            FechaVencimiento = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Prioridad = "Alta",
                            Titulo = "Crear TareasDbContext"
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 2,
                            Completada = false,
                            CreadaEn = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "dotnet ef migrations add",
                            FechaVencimiento = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Prioridad = "Alta",
                            Titulo = "Migraciones y seed"
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 3,
                            Completada = false,
                            CreadaEn = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Skip/Take con conteo total",
                            FechaVencimiento = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Prioridad = "Media",
                            Titulo = "Agregar paginación"
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 4,
                            Completada = false,
                            CreadaEn = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Revisar checklist de entrega",
                            FechaVencimiento = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Prioridad = "Baja",
                            Titulo = "Preparar demo final"
                        });
                });

            modelBuilder.Entity("GestorTareasIntegrador.Models.TareaEntity", b =>
                {
                    b.HasOne("GestorTareasIntegrador.Models.CategoriaEntity", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("GestorTareasIntegrador.Models.CategoriaEntity", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
